version: '3'

services:

  db:
    container_name: project_db
    image:  mysql:5.6
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 3g0zuju6heklku
    ports:
      - 3306:3306

  adminer:
    container_name: project_adminer
    image: adminer
    ports:
      - 8080:8080

  code:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    container_name: project_code
    volumes:
      - ./code:/code:cached
      - ./bundle:/usr/local/bundle:cached
    environment:
      # For production environment
      - SECRET_KEY_BASE=506722546fa18e2d9ae6a2cfcd45e7612fe25777b90960d25abg1tb17115186792d7d27937894dc9be0984150d9d270d89f65404eb8145a8ce3b2uuuu42307
      - DB_USERNAME=root
      - DB_PASSWORD=3g0zuju6heklku
      - DB_HOST=db
      # - RACK_ENV=development
      # - RAILS_SKIP_ASSET_COMPILATION=false
      # - RAILS_SERVE_STATIC_FILES=true
      # - RAILS_LOG_TO_STDOUT=true
      # - RAILS_SKIP_MIGRATIONS=false
      # - BUNDLE_WITHOUT=test:development

    ports:
      - 3001:3001
    depends_on:
      - db
      
